FROM async_deep_reinforce

ADD requirements.test.txt /tmp/requirements.test.txt
RUN pip install -r /tmp/requirements.test.txt

ADD . /root/async_deep_reinforce
WORKDIR /root/async_deep_reinforce

ENTRYPOINT ["py.test"]
CMD ["arg1"]
